"""Moving to back-populates

Revision ID: 1b9aac4afb44
Revises: 8bc7a440938a
Create Date: 2025-08-21 21:49:33.971389

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '1b9aac4afb44'
down_revision: Union[str, Sequence[str], None] = '8bc7a440938a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
