"""Added plot model

Revision ID: 2c47eab5e3d0
Revises: d216516c7b75
Create Date: 2025-08-21 22:14:59.282168

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '2c47eab5e3d0'
down_revision: Union[str, Sequence[str], None] = 'd216516c7b75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
