"""create farm table

Revision ID: 351a5b98611f
Revises: f092cb5f9e76
Create Date: 2025-08-20 18:33:57.903021

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '351a5b98611f'
down_revision: Union[str, Sequence[str], None] = 'f092cb5f9e76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
