"""create farm table - adds relationship for user

Revision ID: 85b7ca03a162
Revises: 8dbc0604a4d5
Create Date: 2025-08-20 19:36:07.344329

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '85b7ca03a162'
down_revision: Union[str, Sequence[str], None] = '8dbc0604a4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
