"""create farm table - adds relationship for user

Revision ID: 8dbc0604a4d5
Revises: 351a5b98611f
Create Date: 2025-08-20 19:31:34.600327

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '8dbc0604a4d5'
down_revision: Union[str, Sequence[str], None] = '351a5b98611f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
