"""create farm table - adds relationship for user

Revision ID: c8fe6412b734
Revises: 85b7ca03a162
Create Date: 2025-08-20 19:39:34.070804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision: str = 'c8fe6412b734'
down_revision: Union[str, Sequence[str], None] = '85b7ca03a162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('boundary', Geography(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('centroid', Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('area_sqm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_farms_boundary', 'farms', ['boundary'], unique=False, postgresql_using='gist')
    op.create_index('idx_farms_centroid', 'farms', ['centroid'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_farms_centroid', table_name='farms', postgresql_using='gist')
    op.drop_index('idx_farms_boundary', table_name='farms', postgresql_using='gist')
    op.drop_table('farms')
    # ### end Alembic commands ###
